version: '3'
services:
  postgres-todo:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_PASSWORD="root"
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: